version: '3.8'

services:
  app:
    image: deminy/yasd-demo
    environment:
      PHP_IDE_CONFIG: "serverName=demo"
    ports:
      - 80:80
    volumes:
      - ./rootfilesystem/usr/local/etc/php/conf.d/docker-php-ext-yasd.ini:/usr/local/etc/php/conf.d/docker-php-ext-yasd.ini
      - ./rootfilesystem/var/www:/var/www
