version: '3.8'

services:
  app:
    image: deminy/yasd-demo
    environment:
      PHP_IDE_CONFIG: "serverName=tnt-server"
    ports:
      - 80:80
    volumes:
      - ./rootfilesystem/usr/local/etc/php/conf.d/docker-php-ext-yasd.ini-suggested:/usr/local/etc/php/conf.d/docker-php-ext-yasd.ini-suggested
      - ./rootfilesystem/var/www:/var/www
      - ./rootfilesystem/entrypoint.sh:/entrypoint.sh
